auctionsonline/auctionsonline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from docutils.nodes import document

urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctionsonline/website/urls.py
from . import views
from django.urls import path

app_name = 'website'

urlpatterns = [
	path('', views.index, name='index'),
	path('login/', views.login_page, name='login_view'),
	path('logout/', views.logout_page, name='logout_view'),
	path('register/', views.register_page, name='register_page'),
	path('register/new_user/', views.register, name='register'),
    path('category/<str:category>/', views.filter_auctions, name='filter_auctions'),
    path('watchlist/<int:auction_id>/', views.watchlist, name='watchlist'),
    path('balance/', views.balance, name='balance'),
    path('balance/topup/', views.topup, name='topup'),
    path('watchlist/', views.watchlist_page, name='watchlist'),
    path('my_items/', views.my_items, name='my_items'),
    path('sell_item/', views.sell_item, name='sell_item' ),
    path('sell_item/save_auction/', views.save_auction, name='save_auction'),
    path('bid/<int:auction_id>/', views.bid_page, name='bid_page'),
    path('bid/<int:auction_id>/comment/', views.comment, name='comment'),
    path('bid/<int:auction_id>/raise_bid/', views.raise_bid, name='raise_bid'),
]

auctionsonline/website/models.py
from django.db import models
from django.utils.timezone import make_aware

# Create your models here.
class User(models.Model):
	username = models.CharField(max_length=45)
	password = models.CharField(max_length=45)
	email = models.EmailField()
	balance = models.DecimalField(max_digits=7, decimal_places=2)
	firstname = models.CharField(max_length=56)
	lastname = models.CharField(max_length=45)
	cellphone = models.CharField(max_length=14)
	address = models.CharField(max_length=255)
	town = models.CharField(max_length=45)
	post_code = models.CharField(max_length=45)
	country = models.CharField(max_length=45)
	
	def __str__(self):
		return "ID:" + str(self.pk) + " " + self.username + " " + self.email

class Product(models.Model):
	CATEGORIES = (
		('HH','Household'),
		('EL','Electronics'),
		('BS','Books and Study Material')
	)
	
	title = models.CharField(max_length=255)
	description = models.CharField(max_length=500)
	base_price = models.IntegerField()
	time_starting = models.DateTimeField()
	category = models.CharField(
		max_length=2,
		choices=CATEGORIES
	)
	image = models.ImageField(upload_to='images/')
	date_posted = models.DateTimeField(auto_now_add=True, blank=True)
	
	def __str__(self):
		return "ID:" + str(self.pk) + " " + self.title

class Auction(models.Model):
	product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
	################
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	################
	base_price = models.IntegerField()
	number_of_bids = models.IntegerField()
	time_starting = models.DateTimeField()
	time_ending = models.DateTimeField()
	
	def __str__(self):
		return "ID:" + str(self.pk) + " PRODUCT_ID:" + str(self.product_id)

class Watchlist(models.Model):
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)
	
	def __str__(self):
		return "USER_ID:" + str(self.user_id) + " AUCTION_ID:" + str(self.auction_id)

class Bid(models.Model):
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)
	bid_time = models.DateTimeField()
	
	def __str__(self):
		return "USER_ID:" + str(self.user_id) + " AUCTION_ID:" + \
			str(self.auction_id) + " " + str(self.bid_time) 

class Chat(models.Model):
	auction_id = models.ForeignKey(Auction, on_delete=models.CASCADE)
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.TextField()
	time_sent = models.DateTimeField()

	def __str__(self):
		return "AUCTION_ID:" + str(self.auction_id) + " USER_ID:" + str(self.user_id)

auctionsonline/website/forms.py
from django import forms
from .models import *

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=45)
    email = forms.EmailField()
    password1 = forms.CharField(max_length=45)
    password2 = forms.CharField(max_length=45)
    firstname = forms.CharField(max_length=56)
    lastname = forms.CharField(max_length=45)
    cellphone = forms.CharField(max_length=45)
    address = forms.CharField(max_length=255)
    town = forms.CharField(max_length=45)
    postcode = forms.CharField(max_length=45)
    country = forms.CharField(max_length=45)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=45)
    password = forms.CharField(max_length=45)

class TopUpForm(forms.Form):
    amount = forms.DecimalField(max_digits=7, decimal_places=2)

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)

class PutUpAuctionForm(forms.Form):
    title = forms.CharField(max_length=45)
    description = forms.CharField(max_length=200)
    time_starting = forms.DateField()
    hour_starting = forms.IntegerField()
    base_price = forms.IntegerField(max_value=200000, min_value=10)
    duration = forms.IntegerField(max_value=20, min_value=1)
    category = forms.CharField(max_length=2)
    image = forms.ImageField()

auctionsonline/website/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.utils import timezone
from django.utils.timezone import make_aware
from datetime import datetime, timedelta
from itertools import chain

from website.forms import *
from website.models import User, Product, Auction, Watchlist, Bid, Chat

from website.validation import validate_login, validate_registration
from website.transactions import increase_bid, remaining_time, update_balance

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders



def index(request):
    """
    The main page of the website

    Returns
    -------
    HTTPResponse
        The index page with the current and future auctions.
    """
    auctions = Auction.objects.filter(time_ending__gte=datetime.now()).order_by('time_starting')

    try:
        if request.session['username']:
            user = User.objects.filter(username=request.session['username'])

            update_balance(user[0])

            auctions = auctions.exclude(user_id=user[0])    # to ensure that user is shown products excluding the ones he set up

            w = Watchlist.objects.filter(user_id=user[0])
            watchlist = Auction.objects.none()
            for item in w:
                a = Auction.objects.filter(id=item.auction_id.id)
                watchlist = list(chain(watchlist, a))

            return render(request, 'index.html', {'auctions': auctions, 'user': user[0], 'watchlist': watchlist})
    except KeyError:
        return render(request, 'index.html', {'auctions': auctions})

    return render(request, 'index.html', {'auctions': auctions})

def bid_page(request, auction_id):
    """
    Returns the bid page for the
    selected auction.

    Parametes
    ---------
    auction_id : class 'int'

    Returns
    -------
    HTTPResponse
        Return the bidding page for the selected auction.
    Function : index(request)
        If the user is not logged in.
    """
    print(type(auction_id))
    try:
        # if not logged in return to the index page.
        if request.session['username']:
            # If the auction hasn't started return to the index page.
            auction = Auction.objects.filter(id=auction_id)
            if auction[0].time_starting > timezone.now():
                return index(request)
            user = User.objects.filter(username=request.session['username'])

            stats = []
            time_left, expired = remaining_time(auction[0])
            stats.append(time_left) # First element in stats list

            current_cost = auction[0].base_price + auction[0].number_of_bids * auction[0].base_price * 0.05
            current_cost = "%0.1f" % current_cost
            stats.append(current_cost)

            # Second element in stats list
            if expired < 0: # if auction ended append false.
                stats.append(False)
            else:
                stats.append(True)

            # Third element in stats list
            latest_bid = Bid.objects.filter(auction_id = auction_id).order_by('-bid_time')
            if latest_bid:
                winner = User.objects.filter(id=latest_bid[0].user_id.id)
                stats.append(winner[0].username)
            else:
                stats.append(None)

            # Fourth element in stats list
            chat = Chat.objects.filter(auction_id = auction_id).order_by('time_sent')
            stats.append(chat)

            # Getting user's watchlist.
            w = Watchlist.objects.filter(user_id=user[0])
            watchlist = Auction.objects.none()
            for item in w:
                a = Auction.objects.filter(id=item.auction_id.id)
                watchlist = list(chain(watchlist, a))

            lastBid = Bid.objects.filter(user_id = user[0].id).filter(auction_id = auction_id).order_by('-bid_time')
            if len(lastBid) !=0:
                nBids_prev = len(Bid.objects.filter( bid_time__lt = lastBid[0].bid_time ))
                userPaid = auction[0].base_price + nBids_prev * 0.05 * auction[0].base_price
                toPay = float(current_cost) - userPaid
            else:
                toPay = current_cost


            if user[0].balance < float(toPay):
                return render(request, 'bid3.html',
                {
                    'auction': auction[0],
                    'user': user[0],
                    'stats': stats,
                    'watchlist':watchlist
                })
            elif len(latest_bid)!=0 and user[0].id == latest_bid[0].user_id.id:
                return render(request, 'bid2.html',
                {
                    'auction': auction[0],
                    'user': user[0],
                    'stats': stats,
                    'watchlist':watchlist
                })

            return render(request, 'bid.html',
            {
                'auction': auction[0],
                'user': user[0],
                'stats': stats,
                'watchlist':watchlist
            })
    except KeyError:
        return index(request)

    return index(request)

def comment(request, auction_id):
    """
    Comment on an auction.

    Returns
    -------
    Function : bid_page(request, auction_id)
        Return the
    Function : index(request)
        If the user is not logged in.
    """
    try:
        if request.session['username']:
            user = User.objects.filter(username=request.session['username'])
            auction = Auction.objects.filter(id=auction_id)
            if request.method == 'POST':
                form = CommentForm(request.POST)
                if form.is_valid():
                    msg = Chat()
                    msg.user_id = user[0]
                    msg.auction_id = auction[0]
                    msg.message = form.cleaned_data['comment']
                    msg.time_sent = timezone.now()
                    msg.save()
                    return bid_page(request, auction_id)

            return index(request)
    except KeyError:
        return index(request)

    return index(request)

def raise_bid(request, auction_id):
    """
    Increases the bid of the selected auction
    and returns to the bidding page.

    Parametes
    ---------
    auction_id : class 'int'

    Returns
    -------
    Function : bid_page(request, auction_id)
        Return the bidding page for the selected auction.
    Function : index(request)
        If the user is not logged in.
    """
    auction = Auction.objects.get(id=auction_id)
    if auction.time_ending < make_aware(datetime.now()):
        return bid_page(request, auction_id)
    elif auction.time_starting > make_aware(datetime.now()):
        return index(request)

    try:
        if request.session['username']:

            user = User.objects.get(username=request.session['username'])

            #increase_bid(user, auction)
            ## need to check if user is latest bidder, if not
            ## then only allow call to increase_bid()


            latest_bid = Bid.objects.filter(auction_id = auction_id).order_by('-bid_time')
            if len(latest_bid) !=0:
                if latest_bid[0].user_id.id == user.id:
                    pass
                else:
                    increase_bid(user, auction)
            else:
                increase_bid(user, auction)
            '''
            user = User.objects.get(username=request.session['username'])
            nBids = Bid.objects.filter(user_id = user.id).filter(auction_id = auction)      # bids the user has already placed in this auction
            currentCost = auction.base_price + auction.number_of_bids * 0.05 * auction.base_price


            if len(nBids)==0:
                toPay = currentCost
            else:
                lastBid = nBids.order_by('-bid_time')[0]
                nBids_prev = len(Bid.objects.filter( bid_time__lt = lastBid.bid_time ))
                userPaid = auction.base_price + nBids_prev * 0.05 * auction.base_price
                toPay = currentCost - userPaid

            if user.balance > toPay:
                latest_bid = Bid.objects.filter(auction_id=auction.id).order_by('-bid_time')
                if not latest_bid:
                    increase_bid(user, auction)
                else:
                    current_winner = User.objects.filter(id=latest_bid[0].user_id.id)
                    if current_winner[0].id != user.id:
                        increase_bid(user, auction)
                    else:
                        # need to load a message saying that current bid is user only, hence can't bid again

            else:
                # need to flash message saying that user has insufficient balance to make bid
            '''
            return bid_page(request, auction_id)
            #return index(request)
    except KeyError:
        return index(request)

    return bid_page(request, auction_id)

def register_page(request):
    """
    Returns the registration page.

    Returns
    -------
    HTTPResponse
        The registration page.
    """
    return render(request, 'register.html')

def watchlist(request, auction_id):
    """
    Adds the auction to the user's watchlist.

    Returns
    -------
    Function : index(request)
    """
    try:
        if request.session['username']:
            user = User.objects.filter(username=request.session['username'])
            auction = Auction.objects.filter(id=auction_id)

            w = Watchlist.objects.filter(auction_id=auction_id)
            if not w:
                watchlist_item = Watchlist()
                watchlist_item.auction_id = auction[0]
                watchlist_item.user_id = user[0]
                watchlist_item.save()
            else:
                w.delete()

        else :
            return index(request)

    except KeyError:
        return index(request)


    return index(request)

auctionsonline/website/templates/balance.html
<!DOCTYPE html>
<html>
<head>
    <title>E-Auction@IITB - Balance Page</title>
    <style>
        #subbut { margin-top: -15px; }
        #upba { margin-top: 70px; }
        #topupform {margin-bottom: 300px; }
    </style>
</head>
<body>
{% extends 'index.html' %}
{% block body %}
    <div id="upba">
        <h2>Update your Balance</h2>
        <hr>
    </div>
    
    <form id="topupform" method="post" action="/website/balance/topup/">{% csrf_token %}
        <div class="form-group">
            <label for="sel1">Select an amount to top-up your balance:</label>
            <select class="form-control" id="sel1" name="amount">
                <option value="500">500₹</option>
                <option value="2000">2000₹</option>
                <option value="10000">10000₹</option>
            </select>
            <br>
        </div>
        <button id="subbut" type="submit" class="btn btn-primary col-sm-12" value="topup">Top Up</button>
    </form>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/bid.html
<!DOCTYPE html>
<html>
<head>
    <title>E-Auction@IITB - Item</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bid.css">
</head>
<body>
{% extends 'index.html' %}
{% block body %}
<div id="bid-flexbox" class="d-flex flex-row">
    <div class="p-2"><img id="preview_product" src="/media/{{ auction.product_id.image }}" /></div>
    <div class="p-2">

        <div id="bidding" class="jumbotron">
            <div id="bid_table">
            <table  class="table table-borderless">
                <tbody>
                    <tr>
                        {% if stats.2 %}
                        <td><small>Time left:</small></td>
                        <td>{{ stats.0 }}</td>
                        {% else %}
                        <p>Auction Ended! The winner is : {{ stats.3 }}</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><small>Current bid:</small></td>
                        <td><b>INR {{stats.1}}₹</b></td>
                        <td><small>[ {{ auction.number_of_bids }} bids ]</small></td>
                    </tr>
                </tbody>
            </table>
            </div>
            {% if stats.2 %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary" onclick="location.href='/website/bid/{{auction.id}}/raise_bid'">Bid</button>
            </div>
            {% endif %}
            <div>
                <button type="button" id="w_button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{auction.id}}'">
                    {% load custom_tags %}
                    {% if watchlist %}
                        {% if watchlist|search:auction.id%}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>

        <div id="comments">
            {% for c in stats.4 %}
            {{ c.user_id.username }} : {{ c.message }}<br>
            {% endfor %}
        </div>

        <form method="post" action="/website/bid/{{auction.id}}/comment/">{% csrf_token %}
        <div class="form-group">
            <label for="comment">Comment:</label>
            <textarea class="form-control" rows="2" id="comment" name="comment"></textarea>
        </div>

        <button id="post_button" type="submit" class="btn btn-outline-primary">Post Comment</button>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/bid2.html
<!DOCTYPE html>
<html>
<head>
    <title>E-Auction@IITB - Item</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bid.css">
</head>
<body>
{% extends 'index.html' %}
{% block body %}
<div id="bid-flexbox" class="d-flex flex-row">
    <div class="p-2"><img id="preview_product" src="/media/{{ auction.product_id.image }}" /></div>
    <div class="p-2">

        <div id="bidding" class="jumbotron">
            <div id="bid_table">
            <table  class="table table-borderless">
                <tbody>
                    <tr>
                        {% if stats.2 %}
                        <td><small>Time left:</small></td>
                        <td>{{ stats.0 }}</td>
                        {% else %}
                        <p>Auction Ended! The winner is : {{ stats.3 }}</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><small>Current bid:</small></td>
                        <td><b>INR {{stats.1}}₹</b></td>
                        <td><small>[ {{ auction.number_of_bids }} bids ]</small></td>
                    </tr>
                </tbody>
            </table>
            </div>
            {% if stats.5 %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary" onclick="location.href='/website/bid/{{auction.id}}/raise_bid'">Bid</button>
            </div>
            {% else %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary">You're the current winning bid</button>
            </div>
            {% endif %}
            <div>
                <button type="button" id="w_button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{auction.id}}'">
                    {% load custom_tags %}
                    {% if watchlist %}
                        {% if watchlist|search:auction.id%}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>

        <div id="comments">
            {% for c in stats.4 %}
            {{ c.user_id.username }} : {{ c.message }}<br>
            {% endfor %}
        </div>

        <form method="post" action="/website/bid/{{auction.id}}/comment/">{% csrf_token %}
        <div class="form-group">
            <label for="comment">Comment:</label>
            <textarea class="form-control" rows="2" id="comment" name="comment"></textarea>
        </div>

        <button id="post_button" type="submit" class="btn btn-outline-primary">Post Comment</button>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/bid3.html
<!DOCTYPE html>
<html>
<head>
    <title>E-Auction@IITB - Item</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bid.css">
</head>
<body>
{% extends 'index.html' %}
{% block body %}
<div id="bid-flexbox" class="d-flex flex-row">
    <div class="p-2"><img id="preview_product" src="/media/{{ auction.product_id.image }}" /></div>
    <div class="p-2">

        <div id="bidding" class="jumbotron">
            <div id="bid_table">
            <table  class="table table-borderless">
                <tbody>
                    <tr>
                        {% if stats.2 %}
                        <td><small>Time left:</small></td>
                        <td>{{ stats.0 }}</td>
                        {% else %}
                        <p>Auction Ended! The winner is : {{ stats.3 }}</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><small>Current bid:</small></td>
                        <td><b>INR {{stats.1}}₹</b></td>
                        <td><small>[ {{ auction.number_of_bids }} bids ]</small></td>
                    </tr>
                </tbody>
            </table>
            </div>
            {% if stats.5 %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary" onclick="location.href='/website/bid/{{auction.id}}/raise_bid'">Bid</button>
            </div>
            {% else %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary">Balance Low</button>
            </div>
            {% endif %}
            <div>
                <button type="button" id="w_button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{auction.id}}'">
                    {% load custom_tags %}
                    {% if watchlist %}
                        {% if watchlist|search:auction.id%}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>

        <div id="comments">
            {% for c in stats.4 %}
            {{ c.user_id.username }} : {{ c.message }}<br>
            {% endfor %}
        </div>

        <form method="post" action="/website/bid/{{auction.id}}/comment/">{% csrf_token %}
        <div class="form-group">
            <label for="comment">Comment:</label>
            <textarea class="form-control" rows="2" id="comment" name="comment"></textarea>
        </div>

        <button id="post_button" type="submit" class="btn btn-outline-primary">Post Comment</button>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>E-Auction@IITB</title>

    <!-- Bootstrap 4.0.0 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <!-- Footer related -->
    <link rel="stylesheet" href="/static/css/footer.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

	<!-- MODAL related - Login -->
	<link rel="stylesheet" type="text/css" href="/static/css/modal.css">

    <!-- ICON -->
    <link rel="icon" href="/static/images/icon.png">

    <!-- PAGE CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">    
    
</head>

<body>

	<!-- Logo -->
	<a href="{% url 'website:index' %}"><img src="/static/images/logosite.png" class="logosite" /></a>

  
    <a href="https://cse.iitb.ac.in"><img src="/static/images/logoinst.png" class="logoinst" align = "right" width="200" height="200">
	
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a id="homebutton" class="navbar-brand" href="{% url 'website:index' %}"><img src="/static/images/home.png" class="logo" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="nav nav-pills">

            <li class="nav-item">
                <a class="nav-link" href="/website/category/household/">Household</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/website/category/electronics/">Electronics</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/website/category/books_and_study_material/">Books and Study Material</a>
            </li>

        </ul>
        
        <ul id="right_navbar" class="navbar-nav ml-auto">
            {% if request.session.username %}

                   {% include "home.html" %}

            {% else %}
            <li class="nav-item open-modal">
                <a id="login" href="#myModal" class="nav-link trigger-btn" data-toggle="modal">Login</a>
            </li>
            <li class="nav-item">
                <a id="signup" class="nav-link" href="/website/register/">Register</a>
            </li>
            {% endif %}
        </ul>
    </nav>
	
	<!-- 
        Products page included with the 
        index page to show all the upcoming 
        Auctions
     -->
    <div class="d-flex justify-content-center">
        <div class="p-2">
            <div id="replacement">
                {% block body %}
				    {% include "products.html" %}
                {% endblock %}
            </div>
        </div>
    </div>

     <footer class="footer-distributed">
        <div class="footer-left">
            <h3>E-Auction<span>@</span><span>IIT-Bombay</span></h3>
            <p class="footer-links">
                <a href="#">Home</a> ·
                <a href="#">About</a> ·
                <a href="#">Faq</a> ·
                <a href="#">Contact</a>
            </p>
            <p class="footer-company-name">E-Auction@IITB &copy; 2019</p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>IIT Bombay</span> Powai, India</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+91 1234567890</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto : admin@gmail.com">admin@gmail.com</a></p>
            </div>
        </div>

        <div class="footer-right">
            <p id="about_store" class="footer-company-about">
                <span>About the store</span>

            </p>
            <div class="footer-icons">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-google"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
            </div>
            <p id="payment_methods" class="footer-company-about">
                <span>Payment methods</span>
            </p>
            <div class="footer-icons">
                <a href="#"><i class="fa fa-cc-visa"></i></a>
                <a href="#"><i class="fa fa-cc-paypal"></i></a>
            </div>
        </div>
    </footer>   
	
	<!-- Login MODAL -->
	<div id="myModal" class="modal fade text-center">
        <div class="modal-dialog">
            <div class="col-lg-8 col-sm-8 col-12 main-section">
                <div class="modal-content">
                    <div class="col-lg-12 col-sm-12 col-12 user-img">
                        <img src="/static/images/man.png">
                    </div>
                    <div class="col-lg-12 col-sm-12 col-12 user-name">
                        <h1>User Login</h1>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="col-lg-12 col-sm-12 col-12 form-input">
                        <form method="post" action="/website/login/">{% csrf_token %}
                            <div class="form-group">
                                <input name="username" type="text" class="form-control" placeholder="Enter username">
                            </div>
                            <div class="form-group">
                                <input name="password" type="password" class="form-control" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>